name: GitHub Action
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run tests
      env:
        name: ${{ secrets.NAME }}
        passwd: ${{ secrets.PASSWD }}
      run: npm test